update .yml file and adding more jobs

diff --git a/.github/workflows/angular-workflow.yml b/.github/workflows/angular-workflow.yml
--- a/.github/workflows/angular-workflow.yml
+++ b/.github/workflows/angular-workflow.yml
@@ -1,4 +1,4 @@
-name: Workspace Build
+name: Angular Frontend CI/CD Workflow
 
 on:
   push:
@@ -6,14 +6,36 @@ on:
       - workspace
 
 jobs:
+
+  # =========== Job 1: Check Files Conditions for specific file changes ===========
+  check-file:
+    name: Check Files
+    runs-on: self-hosted
+
+    steps:
+      - name: Checkout/Clone Code From Repository
+        uses: actions/checkout@v4
+
+      - name: Verify Component Selector
+        run: |
+          if grep -q "selector: 'app-card'" src/app/shared/component/card/card.component.ts; then
+            echo "🟩🟩🟩 Selector found in card.component.ts"
+          else
+            echo "Selector name missing and incorrect 🞫🞫🞫"
+            exit 1
+          fi
+
+  # =========== Job 2: Creating Angular Build ===========
   build:
+    name: Build Angular App
     runs-on: ubuntu-latest
+    needs: check-file
 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Show Message
+      - name: Message For User
         run: echo "Code was pushed to workspace branch. Starting Angular build..."
 
       - name: Setup Node.js
@@ -29,3 +51,22 @@ jobs:
 
       - name: Build Completed
         run: echo "Angular build completed successfully."
+
+  # =========== Job 3: Deploying Angular Application ===========
+  deploy:
+    name: Deploy Angular App
+    runs-on: self-hosted
+    needs: build
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Message For User
+        run: echo "Starting deployment of Angular application..."
+
+      # Add deployment steps here
+      # Example: rsync, scp, Azure, AWS, Nginx server, etc.
+
+      - name: Deployment Completed
+        run: echo "Angular application deployed successfully."
